name: dockerize

on:
    push:
        branches:
            - master
        paths:
            - client/
            - server/
    workflow_dispatch:

jobs:
    build_client:
        name: Build and Push client image
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to GitHub container registry
              uses: docker/login-action@v2
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push client image
              uses: docker/build-push-action@v3
              with:
                  context: ./client
                  file: ./client/Dockerfile
                  push: true
                  tags: ghcr.io/${{ github.repository_owner }}/client:latest

    build_server:
      name: Build and Push server image
      runs-on: ubuntu-latest
      steps:
          - name: Checkout code
            uses: actions/checkout@v3

          - name: Setup Docker Buildx
            uses: docker/setup-buildx-action@v2

          - name: Login to GitHub container registry
            uses: docker/login-action@v2
            with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

          - name: Build and push server image
            uses: docker/build-push-action@v3
            with:
                context: ./server
                file: ./server/Dockerfile
                push: true
                tags: ghcr.io/${{ github.repository_owner }}/server:latest
